# Generated by Django 5.2.5 on 2025-10-22 03:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transacciones', '0005_alter_transaccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisorFacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Emisor')),
                ('ruc', models.CharField(max_length=15, verbose_name='RUC del Emisor')),
                ('dv_ruc', models.CharField(max_length=1, verbose_name='Dígito Verificador del RUC')),
                ('email_emisor', models.EmailField(max_length=254, verbose_name='Email del Emisor')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Casa')),
                ('codigo_departamento', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Departamento')),
                ('descripcion_departamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción Departamento')),
                ('codigo_ciudad', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Ciudad')),
                ('descripcion_ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción Ciudad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('establecimiento', models.CharField(default='001', max_length=3, verbose_name='Establecimiento')),
                ('punto_expedicion', models.CharField(default='003', max_length=3, verbose_name='Punto de Expedición')),
                ('email_equipo', models.EmailField(max_length=254, unique=True, verbose_name='Email del Equipo Asignado')),
                ('rango_numeracion_inicio', models.IntegerField(verbose_name='Inicio del Rango de Numeración')),
                ('rango_numeracion_fin', models.IntegerField(verbose_name='Fin del Rango de Numeración')),
                ('siguiente_numero_factura', models.IntegerField(verbose_name='Siguiente Número de Factura Disponible')),
                ('auth_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='Authentication Token API')),
                ('token_generado_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Generación del Token')),
                ('actividades_economicas', models.JSONField(blank=True, default=list, null=True, verbose_name='Actividades Económicas')),
            ],
            options={
                'verbose_name': 'Emisor de Factura Electrónica',
                'verbose_name_plural': 'Emisores de Facturas Electrónicas',
            },
        ),
        migrations.CreateModel(
            name='DocumentoElectronico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_de', models.CharField(choices=[('factura', 'Factura Electrónica'), ('nota_credito', 'Nota de Crédito Electrónica')], max_length=20, verbose_name='Tipo de Documento Electrónico')),
                ('numero_documento', models.CharField(max_length=7, verbose_name='Número de Documento')),
                ('numero_timbrado', models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de Timbrado')),
                ('cdc', models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Código de Control (CDC)')),
                ('estado_sifen', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación SIFEN'), ('aprobado', 'Aprobado'), ('aprobado_obs', 'Aprobado con Observación'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('inutilizado', 'Inutilizado'), ('error_api', 'Error en API Factura Segura'), ('error_sifen', 'Error en SIFEN'), ('simulado', 'Simulado (Modo Desarrollo)')], default='pendiente_aprobacion', max_length=30, verbose_name='Estado SIFEN')),
                ('descripcion_estado', models.TextField(blank=True, null=True, verbose_name='Descripción del Estado')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Emisión')),
                ('json_enviado_api', models.JSONField(blank=True, null=True, verbose_name='JSON Enviado a API')),
                ('json_respuesta_api', models.JSONField(blank=True, null=True, verbose_name='JSON Respuesta de API')),
                ('url_kude', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Descarga KuDE')),
                ('url_xml', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Descarga XML')),
                ('transaccion_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_electronicos', to='transacciones.transaccion', verbose_name='Transacción Asociada')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_electronicos', to='facturacion_electronica.emisorfacturaelectronica')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'ordering': ['-fecha_emision'],
                'unique_together': {('emisor', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='ItemDocumentoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno')),
                ('descripcion_producto_servicio', models.CharField(max_length=255, verbose_name='Descripción Producto/Servicio')),
                ('unidad_medida', models.CharField(default='77', max_length=5, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Precio Unitario')),
                ('descuento_item', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Descuento por Ítem')),
                ('afectacion_iva', models.CharField(max_length=1, verbose_name='Código de Afectación IVA')),
                ('proporcion_iva', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Proporción Gravada IVA')),
                ('tasa_iva', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tasa IVA')),
                ('documento_electronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion_electronica.documentoelectronico')),
            ],
            options={
                'verbose_name': 'Ítem de Documento Electrónico',
                'verbose_name_plural': 'Ítems de Documentos Electrónicos',
            },
        ),
    ]
