# Generated by Django 5.2.5 on 2025-10-24 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transacciones', '0005_alter_transaccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisorFacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Razón social / Nombre')),
                ('ruc', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{7,8}$')], verbose_name='RUC (sin DV)')),
                ('dv_ruc', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d$')], verbose_name='DV')),
                ('email_emisor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono de contacto')),
                ('codigo_departamento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Dpto (cDepEmi)')),
                ('descripcion_departamento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Desc. Dpto (dDesDepEmi)')),
                ('codigo_ciudad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Ciudad (cCiuEmi)')),
                ('descripcion_ciudad', models.CharField(blank=True, max_length=60, null=True, verbose_name='Desc. Ciudad (dDesCiuEmi)')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección (dDirEmi)')),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True, verbose_name='N° Casa (dNumCas)')),
                ('pais', models.CharField(default='PY', max_length=2, verbose_name='País (cPaisEmi)')),
                ('establecimiento', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$')], verbose_name='Establecimiento (3 dígitos, ej. 001)')),
                ('punto_expedicion', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$')], verbose_name='Punto de expedición (3 dígitos, ej. 003)')),
                ('numero_timbrado_actual', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')], verbose_name='Número de Timbrado (8 dígitos, ej. 02595733)')),
                ('fecha_inicio_timbrado', models.DateField(verbose_name='Fecha de inicio de Timbrado (YYYY-MM-DD)')),
                ('actividad_economica_principal', models.CharField(blank=True, max_length=6, verbose_name='Actividad Económica Principal (cActEco, 6 dígitos)')),
                ('actividades_economicas', models.JSONField(blank=True, default=list, verbose_name='Actividades Económicas adicionales (lista de cActEco)')),
                ('auth_token', models.TextField(blank=True, null=True, verbose_name='Token de autenticación (FacturaSegura)')),
                ('token_generado_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de generación del token')),
                ('activo', models.BooleanField(default=True, verbose_name='Emisor activo')),
                ('rango_numeracion_inicio', models.PositiveIntegerField(default=401, verbose_name='Inicio de numeración')),
                ('rango_numeracion_fin', models.PositiveIntegerField(default=450, verbose_name='Fin de numeración')),
                ('siguiente_numero_factura', models.PositiveIntegerField(default=401, verbose_name='Próximo número a emitir')),
            ],
            options={
                'verbose_name': 'Emisor de Factura Electrónica',
                'verbose_name_plural': 'Emisores de Factura Electrónica',
                'constraints': [models.UniqueConstraint(fields=('ruc', 'dv_ruc', 'establecimiento', 'punto_expedicion', 'numero_timbrado_actual'), name='uniq_emisor_ruc_estab_punto_timbrado')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoElectronico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_de', models.CharField(choices=[('factura', 'Factura Electrónica'), ('nota_credito', 'Nota de Crédito Electrónica')], max_length=20, verbose_name='Tipo de Documento Electrónico')),
                ('numero_documento', models.CharField(max_length=7, verbose_name='Número de Documento')),
                ('numero_timbrado', models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de Timbrado')),
                ('cdc', models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Código de Control (CDC)')),
                ('estado_sifen', models.CharField(choices=[('pendiente_envio', 'Pendiente de envío'), ('pendiente_aprobacion', 'Pendiente de Aprobación SIFEN'), ('pendiente_cancelacion', 'Pendiente de cancelación'), ('pendiente_inutilizacion', 'Pendiente de inutilización'), ('aprobado', 'Aprobado'), ('aprobado_obs', 'Aprobado con Observación'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('inutilizado', 'Inutilizado'), ('error_api', 'Error en API Factura Segura'), ('error_sifen', 'Error en SIFEN'), ('simulado', 'Simulado (Modo Desarrollo)')], default='pendiente_aprobacion', max_length=30, verbose_name='Estado SIFEN')),
                ('descripcion_estado', models.TextField(blank=True, null=True, verbose_name='Descripción del Estado')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Emisión')),
                ('json_enviado_api', models.JSONField(blank=True, null=True, verbose_name='JSON Enviado a API')),
                ('json_respuesta_api', models.JSONField(blank=True, null=True, verbose_name='JSON Respuesta de API')),
                ('url_kude', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Descarga KuDE')),
                ('url_xml', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Descarga XML')),
                ('transaccion_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_electronicos', to='transacciones.transaccion', verbose_name='Transacción Asociada')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_electronicos', to='facturacion_electronica.emisorfacturaelectronica')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'ordering': ['-fecha_emision'],
                'unique_together': {('emisor', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='ItemDocumentoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno')),
                ('descripcion_producto_servicio', models.CharField(max_length=255, verbose_name='Descripción Producto/Servicio')),
                ('unidad_medida', models.CharField(default='77', max_length=5, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Precio Unitario')),
                ('descuento_item', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Descuento por Ítem')),
                ('afectacion_iva', models.CharField(max_length=1, verbose_name='Código de Afectación IVA')),
                ('proporcion_iva', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Proporción Gravada IVA')),
                ('tasa_iva', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tasa IVA')),
                ('documento_electronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion_electronica.documentoelectronico')),
            ],
            options={
                'verbose_name': 'Ítem de Documento Electrónico',
                'verbose_name_plural': 'Ítems de Documentos Electrónicos',
            },
        ),
    ]
