# Generated by Django 5.2.5 on 2025-10-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='descripcion_actividad_economica_principal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción Actividad Económica Principal (dDesActEco)'),
        ),
    ]
