# Generated by Django 5.2.5 on 2025-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Emisor Activo'),
        ),
    ]
