# Generated by Django 5.2.5 on 2025-10-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0002_emisorfacturaelectronica_descripcion_actividad_economica_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='actividades_economicas',
            field=models.JSONField(blank=True, default=list, verbose_name='Actividades Económicas adicionales (lista de cActEco, dDesActEco})'),
        ),
    ]
