# Generated by Django 5.2.5 on 2025-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0002_emisorfacturaelectronica_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='numero_timbrado_actual',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de Timbrado Actual'),
        ),
    ]
