# Generated by Django 5.2.5 on 2025-10-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0003_emisorfacturaelectronica_numero_timbrado_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='fecha_inicio_timbrado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Timbrado'),
        ),
        migrations.AlterField(
            model_name='documentoelectronico',
            name='estado_sifen',
            field=models.CharField(choices=[('pendiente_envio', 'Pendiente de envío'), ('pendiente_aprobacion', 'Pendiente de Aprobación SIFEN'), ('pendiente_cancelacion', 'Pendiente de cancelación'), ('pendiente_inutilizacion', 'Pendiente de inutilización'), ('aprobado', 'Aprobado'), ('aprobado_obs', 'Aprobado con Observación'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('inutilizado', 'Inutilizado'), ('error_api', 'Error en API Factura Segura'), ('error_sifen', 'Error en SIFEN'), ('simulado', 'Simulado (Modo Desarrollo)')], default='pendiente_aprobacion', max_length=30, verbose_name='Estado SIFEN'),
        ),
    ]
