# Generated by Django 5.2.5 on 2025-10-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0003_alter_emisorfacturaelectronica_actividades_economicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='actividad_economica_principal',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='actividades_economicas',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='descripcion_actividad_economica_principal',
        ),
    ]
