# Generated by Django 5.2.5 on 2025-10-23 04:55

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0004_emisorfacturaelectronica_fecha_inicio_timbrado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emisorfacturaelectronica',
            options={'verbose_name': 'Emisor de Factura Electrónica', 'verbose_name_plural': 'Emisores de Factura Electrónica'},
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='email_emisor',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='email_equipo',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='rango_numeracion_fin',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='rango_numeracion_inicio',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='siguiente_numero_factura',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='emisorfacturaelectronica',
            name='token_generado_at',
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='actividad_economica_principal',
            field=models.CharField(blank=True, max_length=6, verbose_name='Actividad Económica Principal (cActEco, 6 dígitos)'),
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='pais',
            field=models.CharField(default='PY', max_length=2, verbose_name='País (cPaisEmi)'),
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='documentoelectronico',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_electronicos', to='facturacion_electronica.emisorfacturaelectronica'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='actividades_economicas',
            field=models.JSONField(blank=True, default=list, verbose_name='Actividades Económicas adicionales (lista de cActEco)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Emisor activo'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='codigo_ciudad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Ciudad (cCiuEmi)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='codigo_departamento',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Dpto (cDepEmi)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='descripcion_ciudad',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Desc. Ciudad (dDesCiuEmi)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='descripcion_departamento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Desc. Dpto (dDesDepEmi)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección (dDirEmi)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='dv_ruc',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d$')], verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='establecimiento',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$')], verbose_name='Establecimiento (3 dígitos, ej. 001)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='fecha_inicio_timbrado',
            field=models.DateField(default=datetime.date(2025, 3, 27), verbose_name='Fecha de inicio de Timbrado (YYYY-MM-DD)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Razón social / Nombre'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='N° Casa (dNumCas)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='numero_timbrado_actual',
            field=models.CharField(default='02595733', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')], verbose_name='Número de Timbrado (8 dígitos, ej. 02595733)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='punto_expedicion',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$')], verbose_name='Punto de expedición (3 dígitos, ej. 003)'),
        ),
        migrations.AlterField(
            model_name='emisorfacturaelectronica',
            name='ruc',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{7,8}$')], verbose_name='RUC (sin DV)'),
        ),
    ]
