# Generated by Django 5.2.5 on 2025-10-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0005_alter_emisorfacturaelectronica_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emisorfacturaelectronica',
            old_name='email_contacto',
            new_name='email_emisor',
        ),
        migrations.RenameField(
            model_name='emisorfacturaelectronica',
            old_name='telefono_contacto',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='auth_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token de autenticación (FacturaSegura)'),
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='rango_numeracion_fin',
            field=models.PositiveIntegerField(default=450, verbose_name='Fin de numeración'),
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='rango_numeracion_inicio',
            field=models.PositiveIntegerField(default=401, verbose_name='Inicio de numeración'),
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='siguiente_numero_factura',
            field=models.PositiveIntegerField(default=401, verbose_name='Próximo número a emitir'),
        ),
        migrations.AddField(
            model_name='emisorfacturaelectronica',
            name='token_generado_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de generación del token'),
        ),
        migrations.AddConstraint(
            model_name='emisorfacturaelectronica',
            constraint=models.UniqueConstraint(fields=('ruc', 'dv_ruc', 'establecimiento', 'punto_expedicion', 'numero_timbrado_actual'), name='uniq_emisor_ruc_estab_punto_timbrado'),
        ),
    ]
