# Generated by Django 5.2.5 on 2025-10-09 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0007_alter_moneda_admite_en_linea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('silenciada', models.BooleanField(default=False, help_text='Si es True, no se muestra en el tablón principal.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('url_destino', models.URLField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciasNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_email_tasa_cambio', models.BooleanField(default=True, help_text='Recibir notificaciones por correo cuando una tasa de interés cambia.')),
                ('monedas_seguidas', models.ManyToManyField(blank=True, help_text='El usuario recibirá notificaciones sobre estas monedas.', related_name='seguidores', to='monedas.moneda')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
    ]
