# Generated by Django 5.2.5 on 2025-10-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('tasa', 'Cambio de Tasa'), ('transaccion', 'Actualización de Transacción'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
