# Generated by Django 5.2.5 on 2025-10-08 04:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedioPago',
            fields=[
                ('id_tipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión que aplica este medio (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de medio de pago',
                'verbose_name_plural': 'Tipos de medios de pago',
                'db_table': 'pagos_tipo_medio',
                'permissions': [('access_pagos_section', 'Puede acceder a la sección de pagos')],
            },
        ),
        migrations.CreateModel(
            name='MedioPagoCliente',
            fields=[
                ('id_medio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(help_text='Nombre para identificar rápidamente este medio', max_length=120)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('predeterminado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='clientes.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_cliente', to='pagos.tipomediopago')),
            ],
            options={
                'verbose_name': 'Medio de pago del cliente',
                'verbose_name_plural': 'Medios de pago del cliente',
                'db_table': 'pagos_medio_cliente',
                'constraints': [models.UniqueConstraint(condition=models.Q(('predeterminado', True)), fields=('cliente',), name='uniq_medio_pago_predeterminado_por_cliente')],
            },
        ),
        migrations.CreateModel(
            name='CampoMedioPago',
            fields=[
                ('id_campo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('telefono', 'Teléfono'), ('email', 'Email'), ('ruc', 'RUC')], default='texto', max_length=15)),
                ('obligatorio', models.BooleanField(default=False)),
                ('regex_opcional', models.CharField(blank=True, choices=[('', '(sin regex)'), ('^\\d+$', 'Solo números'), ('^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$', 'Email básico'), ('^\\+?595\\d{7,10}$', 'Teléfono PY (+595...)'), ('^\\d{6,8}-\\d{1}$', 'RUC PY (########-#)')], default='', max_length=200)),
                ('regex_personalizado', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='pagos.tipomediopago')),
            ],
            options={
                'verbose_name': 'Campo de medio de pago',
                'verbose_name_plural': 'Campos de medios de pago',
                'db_table': 'pagos_campo_medio',
                'unique_together': {('tipo', 'nombre_campo')},
            },
        ),
    ]
