# Generated by Django 5.2.5 on 2025-08-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión en % del monto total ', max_digits=5)),
                ('comision_monto_fijo', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión de monto fijo ', max_digits=10)),
                ('bonificacion_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de bonificación ', max_digits=5)),
                ('es_cuenta_bancaria', models.BooleanField(default=False, help_text='Indica si es una cuenta bancaria (no tiene bonificación)')),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Número de tarjeta, de cuenta, email de la billetera, etc.', max_length=255)),
                ('banco_o_proveedor', models.CharField(blank=True, help_text='Ej: VISA, Banco de Plaza, etc.', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_de_pago', to='clientes.cliente')),
                ('tipo_medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.tipomediopago')),
            ],
            options={
                'verbose_name': 'Medio de Pago del Cliente',
                'verbose_name_plural': 'Medios de Pago del Cliente',
            },
        ),
    ]
