# Generated by Django 5.2.5 on 2025-10-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomediopago',
            name='engine',
            field=models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('sipap', 'SIPAP'), ('simulador', 'Simulador Interno')], default='manual', max_length=20),
        ),
    ]
