# Generated by Django 5.2.5 on 2025-08-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomediopago',
            name='bonificacion_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='comision_monto_fijo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='es_cuenta_bancaria',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MedioDePagoCliente',
        ),
    ]
