# Generated by Django 5.2.5 on 2025-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_tipomediopago_bonificacion_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomediopago',
            options={'verbose_name': 'Tipo de Medio de Pago', 'verbose_name_plural': 'Tipos de Medios de Pago'},
        ),
        migrations.RemoveField(
            model_name='tipomediopago',
            name='bonificacion_porcentaje',
        ),
        migrations.RemoveField(
            model_name='tipomediopago',
            name='comision_monto_fijo',
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión en % del monto total de la transacción', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='es_cuenta_bancaria',
            field=models.BooleanField(default=False, help_text='Indica si es una cuenta bancaria (no se aplican bonificaciones).'),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='nombre',
            field=models.CharField(help_text="Ej. 'Billetera Electrónica', 'Tarjeta de Crédito'", max_length=50, unique=True),
        ),
    ]
