# Generated by Django 5.2.5 on 2025-10-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_tipomediopago_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomediopago',
            name='engine',
            field=models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('sipap', 'SIPAP'), ('local', 'Pasarela Local')], default='manual', max_length=20),
        ),
    ]
