# Generated by Django 5.2.5 on 2025-10-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_campomediopago_regex_personalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomediopago',
            name='regex_opcional',
            field=models.CharField(blank=True, choices=[('', '(sin regex)'), ('^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s]+$', 'Solo letras'), ('^\\d+$', 'Solo números'), ('^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$', 'Email básico'), ('^\\+?595\\d{7,10}$', 'Teléfono PY (+595...)'), ('^\\d{6,8}-\\d{1}$', 'RUC PY (########-#)')], default='', max_length=200),
        ),
    ]
