# Generated by Django 5.2.5 on 2025-10-15 17:34

from django.db import migrations

def update_engine_to_local(apps, schema_editor):
    TipoMedioPago = apps.get_model('pagos', 'TipoMedioPago')
    TipoMedioPago.objects.filter(engine='simulador').update(engine='local')

class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_tipomediopago_engine'),
    ]

    operations = [
        migrations.RunPython(update_engine_to_local),
    ]
