# Generated by Django 5.2.5 on 2025-10-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_campomediopago_regex_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomediopago',
            name='engine',
            field=models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('sipap', 'SIPAP')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='tipomediopago',
            name='engine_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
