# Generated by Django 5.2.5 on 2025-09-14 04:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_tipomediopago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomediopago',
            options={'ordering': ('-activo', 'nombre'), 'verbose_name': 'Tipo de Medio de Pago', 'verbose_name_plural': 'Tipos de Medios de Pago'},
        ),
        migrations.RemoveField(
            model_name='tipomediopago',
            name='es_cuenta_bancaria',
        ),
        migrations.AddField(
            model_name='tipomediopago',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado no se podrá utilizar en operaciones.'),
        ),
        migrations.AddField(
            model_name='tipomediopago',
            name='bonificacion_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento en % aplicado (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tipomediopago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipomediopago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión en % del monto total de la transacción (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='nombre',
            field=models.CharField(help_text="Ej.: 'Tarjeta de Crédito', 'Billetera Electrónica', 'Cheque'", max_length=50, unique=True),
        ),
    ]
