# Generated by Django 5.2.5 on 2025-10-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_update_tipomediopago_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopagocliente',
            name='alias',
            field=models.CharField(max_length=120, verbose_name='Proveedor'),
        ),
    ]
