# Generated by Django 5.2.5 on 2025-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('pagos', '0004_tipomediopago_engine_tipomediopago_engine_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediopagocliente',
            options={},
        ),
        migrations.AlterField(
            model_name='mediopagocliente',
            name='alias',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='mediopagocliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'tipo', 'alias'), name='uniq_alias_por_cliente_y_tipo'),
        ),
    ]
