# Generated by Django 5.2.5 on 2025-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_mediopagocliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomediopago',
            name='regex_opcional',
            field=models.CharField(blank=True, choices=[('', '(sin regex)'), ('^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s]+$', 'Solo letras'), ('^\\d+$', 'Solo números'), ('^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$', 'Email básico'), ('^09\\d{8}$', 'Teléfono PY (09xxxxxxxx)'), ('^\\d{6,8}-\\d{1}$', 'RUC PY (########-#)')], default='', max_length=200),
        ),
    ]
