# Generated by Django 5.2.5 on 2025-10-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_mediopagocliente_alias'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipomediopago',
            table=None,
        ),
    ]
