# Generated by Django 5.2.5 on 2025-10-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_tipomediopago_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campomediopago',
            old_name='id_campo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='mediopagocliente',
            old_name='id_medio',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tipomediopago',
            old_name='id_tipo',
            new_name='id',
        ),
    ]
