# Generated by Django 5.2.5 on 2025-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_rename_id_campo_campomediopago_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomediopago',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediopagocliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipomediopago',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
