# Generated by Django 5.2.5 on 2025-10-31 13:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_alter_campomediopago_id_alter_mediopagocliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomediopago',
            name='bonificacion_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de bonificación que aplica este medio (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
