# Generated by Django 5.2.5 on 2025-10-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_tipomediopago_bonificacion_porcentaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediopagocliente',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mediopagocliente',
            old_name='actualizado_en',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tipomediopago',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tipomediopago',
            old_name='actualizado_en',
            new_name='updated_at',
        ),
    ]
