# Generated by Django 5.2.5 on 2025-10-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_rename_creado_en_mediopagocliente_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campomediopago',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mediopagocliente',
            table=None,
        ),
    ]
