  adan-richar/verificacion-por-correo[m
  adan-richar/verificacion_por_correo[m
* [32mdevelopment[m
  diego/merge-development[m
  master[m
  richar/clase-cliente[m
  richar/crud-cliente[m
  richar/pruebas_unitarias[m
  [31mremotes/origin/Adan/verificacion-por-correo[m
  [31mremotes/origin/AdanPerez-Interfaz[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/adan-richar/verificacion_por_correo[m
  [31mremotes/origin/christian-richar/crud-cliente[m
  [31mremotes/origin/christian/admin-cliente[m
  [31mremotes/origin/christian/clase-usuario-rol[m
  [31mremotes/origin/christian/merge-development[m
  [31mremotes/origin/christian/merge-tres[m
  [31mremotes/origin/christian/pagina-admin[m
  [31mremotes/origin/christian/pruebapostgres[m
  [31mremotes/origin/development[m
  [31mremotes/origin/diego/crud-usuarios[m
  [31mremotes/origin/diego/gestion-roles[m
  [31mremotes/origin/diego/merge-development[m
  [31mremotes/origin/diego/prueba-merge[m
  [31mremotes/origin/eric/integracion-postgresql[m
  [31mremotes/origin/eric/login[m
  [31mremotes/origin/master[m
  [31mremotes/origin/richar/clase-cliente[m
  [31mremotes/origin/richar/crud-cliente[m
  [31mremotes/origin/richar/pruebas_unitarias[m
