# Generated by Django 5.2.5 on 2025-08-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='admite_efectivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='admite_en_linea',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='admite_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moneda',
            name='decimales',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='moneda',
            name='limite_transaccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='minima_denominacion',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='ultima_actualizacion_tasa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
