# Generated by Django 5.2.5 on 2025-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0002_moneda_admite_efectivo_moneda_admite_en_linea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='minima_denominacion',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
