# Generated by Django 5.2.5 on 2025-08-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0003_alter_moneda_minima_denominacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='limite_transaccion',
        ),
    ]
