# Generated by Django 5.2.5 on 2025-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0004_remove_moneda_limite_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='admite_efectivo',
        ),
        migrations.AlterField(
            model_name='moneda',
            name='admite_terminal',
            field=models.BooleanField(default=True),
        ),
    ]
