# Generated by Django 5.2.5 on 2025-09-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0005_remove_moneda_admite_efectivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'permissions': [('access_monedas_section', 'Puede acceder a la sección de Monedas')]},
        ),
    ]
