# Generated by Django 5.2.5 on 2025-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0006_alter_moneda_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='admite_en_linea',
            field=models.BooleanField(default=True, help_text='Si está activo, la moneda puede usarse en operaciones en línea.'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='admite_terminal',
            field=models.BooleanField(default=True, help_text='Si está activo, la moneda puede usarse en operaciones de terminal.'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='codigo',
            field=models.CharField(help_text='Código ISO/corto de la moneda (p. ej. USD, EUR, PYG). Debe ser único.', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='decimales',
            field=models.PositiveSmallIntegerField(default=2, help_text='Cantidad de decimales con los que se representa la moneda (por defecto: 2).'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro (asignado automáticamente).'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='minima_denominacion',
            field=models.PositiveIntegerField(default=1, help_text='Mínima denominación operable (p. ej., 1, 5, 10).'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(help_text='Nombre legible de la moneda (p. ej. Dólar estadounidense).', max_length=50),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(help_text='Símbolo de la moneda (p. ej. $, €, ₲).', max_length=5),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='ultima_actualizacion_tasa',
            field=models.DateTimeField(blank=True, help_text='Última fecha/hora en la que se actualizó la tasa/cotización. Puede ser nulo.', null=True),
        ),
    ]
