# Generated by Django 5.2.5 on 2025-09-25 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0007_alter_moneda_admite_en_linea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TedDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(help_text='Valor facial (entero) de la denominación. Ej.: 1, 2, 5, 10, 20, 50, 100.')),
                ('activa', models.BooleanField(default=True)),
                ('moneda', models.ForeignKey(help_text='Moneda a la que pertenece la denominación.', on_delete=django.db.models.deletion.PROTECT, related_name='denominaciones_ted', to='monedas.moneda')),
            ],
            options={
                'ordering': ['moneda__codigo', 'valor'],
                'permissions': [('access_ted_inventory', 'Puede gestionar el inventario del TED')],
                'unique_together': {('moneda', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='TedInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denominacion', models.OneToOneField(help_text='Denominación cuyo stock se registra.', on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='monedas.teddenominacion')),
            ],
            options={
                'ordering': ['denominacion__moneda__codigo', 'denominacion__valor'],
            },
        ),
        migrations.CreateModel(
            name='TedMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Variación de stock. Positivo suma, negativo resta.')),
                ('motivo', models.CharField(choices=[('AJUSTE', 'Ajuste manual'), ('COMPRA', 'Compra cliente (retiro billetes)'), ('VENTA', 'Venta cliente (depósito billetes)'), ('CHEQUE', 'Depósito de cheque (mock)'), ('OTRO', 'Otro')], default='OTRO', max_length=12)),
                ('transaccion_ref', models.CharField(blank=True, help_text='Referencia textual/ID externo de la transacción (opcional).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_ted', to=settings.AUTH_USER_MODEL)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='monedas.teddenominacion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
