# Generated by Django 5.2.5 on 2025-10-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0010_tedinventario_unique_den_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tedinventario',
            options={'ordering': ['denominacion__moneda__codigo', 'denominacion__valor', 'ubicacion']},
        ),
    ]
