# Generated by Django 5.2.5 on 2025-11-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0011_alter_tedinventario_options'),
        ('transacciones', '0005_alter_transaccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGanancia',
            fields=[
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_ganancia', serialize=False, to='transacciones.transaccion')),
                ('ganancia_registrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moneda_ganancia', models.ForeignKey(help_text='Moneda en la que se registra la ganancia (ej. PYG).', on_delete=django.db.models.deletion.PROTECT, related_name='ganancias_en_pyg', to='monedas.moneda')),
                ('moneda_operada', models.ForeignKey(help_text='Moneda extranjera de la transacción (ej. USD, EUR).', on_delete=django.db.models.deletion.PROTECT, related_name='ganancias_por_moneda', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Registro de Ganancia',
                'verbose_name_plural': 'Registros de Ganancias',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
