# Generated by Django 5.2.5 on 2025-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganancias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroganancia',
            name='fecha_registro',
            field=models.DateTimeField(db_index=True),
        ),
    ]
