# Generated by Django 5.2.5 on 2025-09-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_admin_dashboard', 'Puede acceder al dashboard del Admin Panel')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
