# Generated by Django 5.2.5 on 2025-09-24 02:37

import configuracion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0007_alter_moneda_admite_en_linea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_diario', models.BooleanField(default=True)),
                ('monto_diario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aplica_mensual', models.BooleanField(default=False)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('moneda', models.ForeignKey(default=configuracion.models.get_moneda_base, editable=False, on_delete=django.db.models.deletion.CASCADE, to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Límite de Transacción',
                'verbose_name_plural': 'Límites de Transacción',
            },
        ),
    ]
