# Generated by Django 5.2.5 on 2025-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlimit',
            name='monto_diario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionlimit',
            name='monto_mensual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
