# Generated by Django 5.2.5 on 2025-10-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_transactionlimit_monto_diario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlimit',
            options={'permissions': [('access_config_panel', 'Puede acceder al panel de Configuración')], 'verbose_name': 'Límite de Transacción', 'verbose_name_plural': 'Límites de Transacción'},
        ),
    ]
