# Generated by Django 5.2.5 on 2025-09-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ted', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tedperms',
            options={'permissions': [('puede_operar_terminal', 'Puede operar el terminal TED'), ('puede_gestionar_inventario', 'Puede gestionar inventario TED')]},
        ),
    ]
