# Generated by Django 5.2.5 on 2025-10-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ted', '0002_alter_tedperms_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TedTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Serial')),
                ('direccion', models.CharField(blank=True, default='', max_length=200, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terminal TED',
                'verbose_name_plural': 'Terminales TED',
            },
        ),
    ]
