"""
Django settings for CasaDeCambioIS2 project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path
import dj_database_url
from datetime import timedelta

# --- Paths base ---
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Seguridad / Debug ---
# Sugerencia: lee SECRET_KEY desde variable de entorno en producción; dejamos fallback para desarrollo.
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-yhfkpx7h5kqtf2zv&2vm*a)kc-47@l0wro4xbu_ty7$-3p8jgt"
)  # ⚠️ En prod, define DJANGO_SECRET_KEY en el entorno

DEBUG = True

ALLOWED_HOSTS = [
    "casa-de-cambio.herokuapp.com",
    "127.0.0.1",
    "*",  # Útil para desarrollo inicial; en prod, restringe esto.
]


# --- Apps instaladas ---
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "lib",
    "usuarios",
    "clientes",
    "roles",
    "monedas",
]


# --- Middleware ---
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Para servir estáticos en prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# --- URLs / WSGI ---
ROOT_URLCONF = "CasaDeCambioIS2.urls"
WSGI_APPLICATION = "CasaDeCambioIS2.wsgi.application"


# --- Templates ---
# Cambiamos a Pathlib y aseguramos que use /templates en la raíz del proyecto.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # <— Ajuste recomendado
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# --- Base de datos ---
# Para desarrollo local usamos sqlite; tu config previa REMOTA queda comentada.
# DATABASES = {
#     "default": dj_database_url.config(conn_max_age=600)
# }
DATABASES = {
    'default': {
        'NAME': 'casadecambio_db',         # El nombre de la BD que creaste en el paso 2
        'ENGINE': 'django.db.backends.postgresql',
        'USER': 'casadecambio_user',       # El usuario que creaste
        'PASSWORD': 'una_contraseña_muy_segura', # La contraseña que elegiste
        'HOST': 'localhost',               # O '127.0.0.1'. Se conecta a la BD en la misma máquina
        'PORT': '5432',                    # El puerto por defecto de PostgreSQL
    }
}
AUTH_USER_MODEL = 'usuarios.CustomUser'
# Configuración de correo (ejemplo con Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'richarcarballo.rc@fpuna.edu.py'
EMAIL_HOST_PASSWORD = 'kkvk hevn lbkf ywta'  # Usar contraseña de aplicación

# --- Validadores de password ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# --- Internacionalización ---
# (Opcional, recomendado para tu contexto)
LANGUAGE_CODE = "es"  # <— Antes: 'en-us'
TIME_ZONE = "America/Asuncion"  # <— Antes: 'UTC'
USE_I18N = True
USE_TZ = True


# --- Archivos estáticos ---
# ✅ Unificamos a una sola definición de STATIC_URL y añadimos STATICFILES_DIRS.
STATIC_URL = "/static/"  # <— Deja solo esta (antes tenías duplicado)

# Carpeta de estáticos en desarrollo (al lado de manage.py)
STATICFILES_DIRS = [BASE_DIR / "static"]  # <— NUEVO: para encontrar /static en dev

# Carpeta a la que collectstatic copiará todo para producción
STATIC_ROOT = BASE_DIR / "staticfiles"

# Recomendado para producción con WhiteNoise (actívalo cuando hagas collectstatic):
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# --- Modelo de usuario ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "usuarios.CustomUser"


# --- DRF / JWT ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,  # Reutiliza la SECRET_KEY (ideal si viene del entorno)
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}