# Generated by Django 5.2.5 on 2025-10-12 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPagoSimulado',
            fields=[
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, help_text='El hash único que identifica el pedido en la pasarela.', primary_key=True, serialize=False)),
                ('transaccion_id', models.CharField(max_length=36, unique=True)),
                ('datos_pedido', models.JSONField()),
                ('url_notificacion', models.URLField()),
                ('url_retorno', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido de Pago Simulado',
                'verbose_name_plural': 'Pedidos de Pago Simulados',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
