# Generated by Django 5.2.5 on 2025-10-14 21:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSimulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_comercio', models.UUIDField(help_text='El ID de la Transaccion en el sistema principal.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=255)),
                ('url_confirmacion', models.URLField(help_text='URL (webhook) a la que se notificará el resultado del pago.')),
                ('url_retorno', models.URLField(help_text='URL a la que se redirigirá al cliente después del pago.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación del usuario'), ('PROCESADO', 'Procesado (Webhook enviado)')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago Simulado',
                'verbose_name_plural': 'Pagos Simulados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='PedidoPagoSimulado',
        ),
    ]
