# Generated by Django 5.2.5 on 2025-08-20 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre descriptivo del permiso (ej. 'Crear Cliente')", max_length=100, unique=True)),
                ('codigo', models.CharField(help_text="Código único para usar en el código (ej. 'crear_cliente')", max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('permisos', models.ManyToManyField(related_name='roles', to='usuarios.permiso')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.OneToOneField(blank=True, help_text='Rol asignado a este usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol'),
        ),
    ]
