# Generated by Django 5.2.5 on 2025-08-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20250820_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
