# Generated by Django 5.2.5 on 2025-08-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permiso_rol_customuser_rol'),
        ('usuarios', '0004_remove_customuser_tipo_usuario_and_more'),
    ]

    operations = [
    ]
