# Generated by Django 5.2.5 on 2025-08-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_merge_20250821_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
