# Generated by Django 5.2.5 on 2025-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_customuser_roles_customuser_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ANALISTA', 'Analista'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=50),
        ),
    ]
