# Generated by Django 5.2.5 on 2025-08-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0008_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='clientes.cliente'),
        ),
    ]
