# Generated by Django 5.2.5 on 2025-08-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_customuser_options_alter_customuser_managers_and_more'),
        ('usuarios', '0010_customuser_role'),
    ]

    operations = [
    ]
