# Generated by Django 5.2.5 on 2025-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_customuser_role_customuser_code_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_user_client_management', 'Puede gestionar usuarios y clientes')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
