# Generated by Django 5.2.5 on 2025-10-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('usuarios', '0013_usuariospermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clientes',
            field=models.ManyToManyField(blank=True, help_text='Clientes que este usuario puede gestionar o con los que puede operar.', related_name='usuarios_asociados', to='clientes.cliente'),
        ),
    ]
