# Generated by Django 5.2.5 on 2025-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('usuarios', '0014_alter_customuser_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clientes',
            field=models.ManyToManyField(related_name='usuarios', to='clientes.cliente', verbose_name='Clientes asociados'),
        ),
    ]
