# Generated by Django 5.2.5 on 2025-10-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_customuser_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariospermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_user_client_management', 'Puede gestionar usuarios y clientes'), ('access_dashboard_cliente', 'Puede acceder al dashboard de clientes')]},
        ),
    ]
