# Generated by Django 5.2.5 on 2025-10-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_usuariospermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariospermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_user_client_management', 'Puede gestionar usuarios y clientes')]},
        ),
    ]
