# Generated by Django 5.2.5 on 2025-09-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Banco Itaú, Tigo Money', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('banco', 'Cuenta Bancaria'), ('billetera', 'Billetera Electrónica')], max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este canal está operativo para transacciones.')),
            ],
            options={
                'verbose_name': 'Canal Financiero',
                'verbose_name_plural': 'Canales Financieros',
            },
        ),
        migrations.CreateModel(
            name='Tauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificador', models.CharField(help_text='ID único de la terminal. Ej: TAUSER-001', max_length=20, unique=True)),
                ('ubicacion', models.CharField(help_text='Dirección o descripción de la ubicación de la terminal.', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la terminal está operativa.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terminal de Autoservicio (Tauser)',
                'verbose_name_plural': 'Terminales de Autoservicio (Tauser)',
            },
        ),
    ]
