# Generated by Django 5.2.5 on 2025-09-22 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('monedas', '0007_alter_moneda_admite_en_linea_and_more'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'clientes_medioacreditacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta de Divisa'), ('compra', 'Compra de Divisa')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente_pago_cliente', 'Pendiente de Pago del Cliente (PYG)'), ('pendiente_retiro_tauser', 'Pendiente de Retiro de Divisa (Tauser)'), ('pendiente_deposito_tauser', 'Pendiente de Depósito de Divisa (Tauser)'), ('procesando_acreditacion', 'Procesando Acreditación a Cliente (PYG)'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('error', 'Error')], max_length=30)),
                ('monto_origen', models.DecimalField(decimal_places=2, help_text='Monto que entrega la parte que inicia.', max_digits=15)),
                ('monto_destino', models.DecimalField(decimal_places=2, help_text='Monto que recibe la contraparte.', max_digits=15)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('comision_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_operacion_tauser', models.CharField(help_text='Código único para que el cliente opere en el Tauser.', max_length=10, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
                ('medio_acreditacion_cliente', models.ForeignKey(blank=True, help_text='Cuenta del cliente donde se acreditarán los fondos (solo en COMPRA de divisa).', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.medioacreditacion')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='monedas.moneda')),
                ('tauser_utilizado', models.ForeignKey(blank=True, help_text='Terminal donde se realizó el depósito/retiro físico.', null=True, on_delete=django.db.models.deletion.PROTECT, to='operaciones.tauser')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
