# Generated by Django 5.2.5 on 2025-10-15 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('monedas', '0008_teddenominacion_tedinventario_tedmovimiento'),
        ('operaciones', '0001_initial'),
        ('pagos', '0002_alter_tipomediopago_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'clientes_medioacreditacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta de Divisa'), ('compra', 'Compra de Divisa')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente_pago_cliente', 'Pendiente de Pago del Cliente (PYG)'), ('pendiente_retiro_tauser', 'Pendiente de Retiro de Divisa (Tauser)'), ('pendiente_deposito_tauser', 'Pendiente de Depósito de Divisa (Tauser)'), ('procesando_acreditacion', 'Procesando Acreditación a Cliente (PYG)'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('cancelada_usuario_tasa', 'Cancelada por Usuario (Variación de Tasa)'), ('cancelada_tasa_expirada', 'Cancelada (Tasa Expirada)'), ('anulada', 'Anulada'), ('error', 'Error')], max_length=30)),
                ('monto_origen', models.DecimalField(decimal_places=2, help_text='Monto que entrega la parte que inicia.', max_digits=15)),
                ('monto_destino', models.DecimalField(decimal_places=2, help_text='Monto que recibe la contraparte.', max_digits=15)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('comision_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_operacion_tauser', models.CharField(help_text='Código único para que el cliente opere en el Tauser.', max_length=10, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tasa_garantizada_hasta', models.DateTimeField(blank=True, help_text='Fecha y hora límite para honrar la tasa garantizada.', null=True)),
                ('modalidad_tasa', models.CharField(choices=[('bloqueada', 'Tasa Bloqueada'), ('flotante', 'Tasa Flotante (Indicativa)')], default='bloqueada', help_text='Define si la tasa es fija por un tiempo o indicativa.', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_cliente', to='clientes.cliente')),
                ('medio_acreditacion_cliente', models.ForeignKey(blank=True, help_text='Cuenta del cliente donde se acreditarán los fondos (solo en COMPRA de divisa).', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.medioacreditacion')),
                ('medio_pago_utilizado', models.ForeignKey(blank=True, help_text='Medio de pago utilizado por el cliente para pagar (solo en VENTA de divisa).', null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.tipomediopago')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='monedas.moneda')),
                ('tauser_utilizado', models.ForeignKey(blank=True, help_text='Terminal donde se realizó el depósito/retiro físico.', null=True, on_delete=django.db.models.deletion.PROTECT, to='operaciones.tauser')),
                ('usuario_operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
