# Generated by Django 5.2.5 on 2025-09-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago_cliente', 'Pendiente de Pago del Cliente (PYG)'), ('pendiente_retiro_tauser', 'Pendiente de Retiro de Divisa (Tauser)'), ('pendiente_deposito_tauser', 'Pendiente de Depósito de Divisa (Tauser)'), ('procesando_acreditacion', 'Procesando Acreditación a Cliente (PYG)'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada'), ('error', 'Error')], max_length=30),
        ),
    ]
