# Generated by Django 5.2.5 on 2025-10-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_add_medio_pago_utilizado'),
    ]

    operations = [
    ]
