# Generated by Django 5.2.5 on 2025-09-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tasa_garantizada_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite para honrar la tasa garantizada.', null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago_cliente', 'Pendiente de Pago del Cliente (PYG)'), ('pendiente_retiro_tauser', 'Pendiente de Retiro de Divisa (Tauser)'), ('pendiente_deposito_tauser', 'Pendiente de Depósito de Divisa (Tauser)'), ('procesando_acreditacion', 'Procesando Acreditación a Cliente (PYG)'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('cancelada_usuario_tasa', 'Cancelada por Usuario (Variación de Tasa)'), ('anulada', 'Anulada'), ('error', 'Error')], max_length=30),
        ),
    ]
