# Generated by Django 5.2.5 on 2025-09-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_transaccion_tasa_garantizada_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='modalidad_tasa',
            field=models.CharField(choices=[('bloqueada', 'Tasa Bloqueada'), ('flotante', 'Tasa Flotante (Indicativa)')], default='bloqueada', help_text='Define si la tasa es fija por un tiempo o indicativa.', max_length=10),
        ),
    ]
