# Generated by Django 5.2.5 on 2025-10-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_merge_20251017_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente_confirmacion_pago', 'Pendiente de Confirmación de Pago'), ('pendiente_pago_cliente', 'Pendiente de Pago del Cliente (PYG)'), ('pendiente_retiro_tauser', 'Pendiente de Retiro de Divisa (Tauser)'), ('pendiente_deposito_tauser', 'Pendiente de Depósito de Divisa (Tauser)'), ('procesando_acreditacion', 'Procesando Acreditación a Cliente (PYG)'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('cancelada_usuario_tasa', 'Cancelada por Usuario (Variación de Tasa)'), ('cancelada_tasa_expirada', 'Cancelada (Tasa Expirada)'), ('anulada', 'Anulada'), ('error', 'Error')], max_length=30),
        ),
    ]
