# Generated by Django 5.2.5 on 2025-11-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comision_cotizacion',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Comisión de compra/venta de la cotización en el momento de la transacción.', max_digits=10),
        ),
    ]
