# Generated by Django 5.2.5 on 2025-10-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_alter_transaccion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cliente',
        ),
    ]
