# Generated by Django 5.2.5 on 2025-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0006_transaccion_comision_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='datos_medio_acreditacion_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Instantánea de los datos del medio de acreditación del cliente al momento de la transacción.', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='datos_medio_pago_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Instantánea de los datos del medio de pago del cliente al momento de la transacción.', null=True),
        ),
    ]
