# Generated by Django 5.2.5 on 2025-10-02 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('transacciones', '0006_remove_transaccion_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_cliente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario_operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
