# Generated by Django 5.2.5 on 2025-10-02 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('transacciones', '0007_transaccion_cliente_transaccion_usuario_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(default='b1fccb00-0d1c-4ff9-cc7e-7cc0ce491b22', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_cliente', to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='usuario_operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_realizadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
