# Generated by Django 5.2.5 on 2025-12-11 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('pagos', '0005_alter_mediopagocliente_alias'),
        ('transacciones', '0007_transaccion_datos_medio_acreditacion_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='medio_acreditacion_cliente',
            field=models.ForeignKey(blank=True, help_text='Cuenta del cliente donde se acreditarán los fondos (solo en COMPRA de divisa).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.medioacreditacion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='medio_pago_utilizado',
            field=models.ForeignKey(blank=True, help_text='Medio de pago utilizado por el cliente para pagar (solo en VENTA de divisa).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.tipomediopago'),
        ),
    ]
