# Generated by Django 5.2.5 on 2025-09-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_roles_panel', 'Puede acceder al panel de Roles'), ('delete_roles', 'Puede eliminar roles')], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
