# Generated by Django 5.2.5 on 2025-08-21 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID del cliente')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo o razón social')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico verificado')),
                ('categoria', models.CharField(choices=[('minorista', 'Minorista'), ('corporativo', 'Corporativo'), ('vip', 'VIP')], default='minorista', max_length=20, verbose_name='Categoría del cliente')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
