# Generated by Django 5.2.5 on 2025-09-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo_electronico',
        ),
    ]
