# Generated by Django 5.2.5 on 2025-09-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_correo_electronico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'permissions': [('access_clientes_panel', 'Puede acceder al panel de clientes')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
