# Generated by Django 5.2.5 on 2025-09-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_options'),
        ('clientes', '0003_remove_cliente_user'),
    ]

    operations = [
    ]
