# Generated by Django 5.2.5 on 2025-09-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_merge_20250914_0029'),
        ('clientes', '0004_merge_20250914_0108'),
    ]

    operations = [
    ]
