# Generated by Django 5.2.5 on 2025-09-22 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_merge_20250914_2011'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Número de cuenta, CBU, Número de Teléfono, etc.', max_length=100)),
                ('alias', models.CharField(blank=True, help_text='Un nombre fácil de recordar para este medio.', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(help_text='Entidad financiera soportada por la casa de cambio.', on_delete=django.db.models.deletion.PROTECT, to='operaciones.canalfinanciero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medio de Acreditación',
                'verbose_name_plural': 'Medios de Acreditación',
                'unique_together': {('cliente', 'canal', 'identificador')},
            },
        ),
    ]
