# Generated by Django 5.2.5 on 2025-08-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_venta', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moneda_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_base', to='monedas.moneda')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_destino', to='monedas.moneda')),
            ],
            options={
                'unique_together': {('moneda_base', 'moneda_destino')},
            },
        ),
    ]
