# Generated by Django 5.2.5 on 2025-09-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'permissions': [('access_cotizaciones', 'Puede acceder a la sección de cotizaciones')]},
        ),
    ]
