# Generated by Django 5.2.5 on 2025-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='comision_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='comision_venta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
