# Generated by Django 5.2.5 on 2025-09-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_cotizacion_options'),
        ('cotizaciones', '0002_cotizacion_comision_compra_cotizacion_comision_venta'),
    ]

    operations = [
    ]
