# Generated by Django 5.2.5 on 2025-09-15 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_merge_20250906_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='comision_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='comision_venta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='valor_compra',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='valor_venta',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
