# Generated by Django 5.2.5 on 2025-10-31 07:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_alter_cotizacion_comision_compra_and_more'),
        ('monedas', '0011_alter_tedinventario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comision_compra', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_venta', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comision_venta', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fuente', models.CharField(blank=True, default='', max_length=40)),
                ('moneda_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hist_base', to='monedas.moneda')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hist_destino', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Cotización histórica',
                'verbose_name_plural': 'Cotizaciones históricas',
                'indexes': [models.Index(fields=['moneda_base', 'moneda_destino', 'fecha'], name='idx_hist_pair_fecha')],
            },
        ),
    ]
