# Generated by Django 5.2.5 on 2025-09-21 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_merge_20250914_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CUENTA_SIPAP', 'Cuenta bancaria (SIPAP)'), ('BILLETERA', 'Billetera electrónica')], max_length=20)),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('moneda', models.CharField(default='PYG', editable=False, max_length=3)),
                ('titular_nombre', models.CharField(max_length=120)),
                ('titular_documento', models.CharField(max_length=40)),
                ('entidad_financiera', models.CharField(blank=True, max_length=80)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=40)),
                ('numero_cuenta_cbu', models.CharField(blank=True, max_length=48)),
                ('proveedor', models.CharField(blank=True, max_length=60)),
                ('identificador_billetera', models.CharField(blank=True, max_length=80)),
                ('habilitado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('verificacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Medio de acreditación',
                'verbose_name_plural': 'Medios de acreditación',
                'permissions': [('access_medios_acreditacion_section', 'Puede acceder a la sección Medios de Acreditación')],
            },
        ),
    ]
