# Generated by Django 5.2.5 on 2025-09-21 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CUENTA_SIPAP', 'Cuenta bancaria (SIPAP)'), ('BILLETERA', 'Billetera electrónica')], help_text='Selecciona el tipo de medio de acreditación permitido en el sistema.', max_length=40)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Comisión en % del monto total (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bonificacion_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Descuento/bonificación en % aplicado (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no se podrá usar en operaciones.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Medio de Acreditación',
                'verbose_name_plural': 'Tipos de Medio de Acreditación',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.DeleteModel(
            name='MedioAcreditacion',
        ),
    ]
