# Generated by Django 5.2.5 on 2025-09-21 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_merge_20250914_2011'),
        ('medios_acreditacion', '0002_tipomedioacreditacion_delete_medioacreditacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text="Nombre visible para el cliente (p. ej.: 'Itaú - Ahorros').", max_length=80)),
                ('tipo', models.CharField(choices=[('CUENTA', 'Cuenta Bancaria (SIPAP)'), ('BILLETERA', 'Billetera Electrónica'), ('PICKUP', 'Retiro en Caja (Pickup)')], max_length=12)),
                ('entidad_financiera', models.CharField(blank=True, help_text='Banco/entidad financiera.', max_length=80)),
                ('numero_cuenta', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^[0-9\\-\\.]+$', 'Solo dígitos y separadores (- .)')])),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORROS', 'Caja de Ahorros'), ('CORRIENTE', 'Cuenta Corriente')], max_length=20)),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor de la billetera (p. ej.: Tigo Money).', max_length=80)),
                ('billetera_alias', models.CharField(blank=True, help_text='Número/alias de la billetera.', max_length=60)),
                ('punto_retiro', models.CharField(blank=True, help_text='Punto/sucursal para retiro en caja.', max_length=120)),
                ('moneda', models.CharField(default='PYG', editable=False, max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente propietario del medio.', on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Medio de Acreditación',
                'verbose_name_plural': 'Medios de Acreditación',
                'ordering': ('-activo', 'alias'),
            },
        ),
        migrations.DeleteModel(
            name='TipoMedioAcreditacion',
        ),
        migrations.AddConstraint(
            model_name='medioacreditacion',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_cuenta__gt', '')), fields=('cliente', 'tipo', 'numero_cuenta'), name='uniq_medio_cuenta_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='medioacreditacion',
            constraint=models.UniqueConstraint(condition=models.Q(('billetera_alias__gt', '')), fields=('cliente', 'tipo', 'billetera_alias'), name='uniq_medio_billetera_por_cliente'),
        ),
    ]
