# Generated by Django 5.2.5 on 2025-09-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0003_medioacreditacion_delete_tipomedioacreditacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medioacreditacion',
            name='uniq_medio_cuenta_por_cliente',
        ),
        migrations.RemoveConstraint(
            model_name='medioacreditacion',
            name='uniq_medio_billetera_por_cliente',
        ),
        migrations.RenameField(
            model_name='medioacreditacion',
            old_name='created_at',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='medioacreditacion',
            old_name='updated_at',
            new_name='ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='medioacreditacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='medioacreditacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='medioacreditacion',
            name='categoria',
            field=models.CharField(choices=[('CUENTA_BANCARIA', 'Cuenta Bancaria (SIPAP)'), ('BILLETERA', 'Billetera Electrónica'), ('CAJA', 'Retiro en Caja')], default='CUENTA_BANCARIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='medioacreditacion',
            name='alias',
            field=models.CharField(help_text="Nombre visible. Ej.: 'Itaú - CC principal', 'Caja Central'.", max_length=80),
        ),
        migrations.AlterField(
            model_name='medioacreditacion',
            name='billetera_alias',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='medioacreditacion',
            name='entidad_financiera',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='medioacreditacion',
            name='proveedor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='medioacreditacion',
            name='punto_retiro',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
