# Generated by Django 5.2.5 on 2025-09-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0004_remove_medioacreditacion_uniq_medio_cuenta_por_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del medio de acreditación (ej.: Cuenta Bancaria, Billetera Electrónica).', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve de este tipo de medio.')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no se podrá usar este tipo de medio en nuevas operaciones.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Medio de Acreditación',
                'verbose_name_plural': 'Tipos de Medios de Acreditación',
                'ordering': ('-activo', 'nombre'),
            },
        ),
        migrations.DeleteModel(
            name='MedioAcreditacion',
        ),
    ]
