# Generated by Django 5.2.5 on 2025-09-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0005_tipomedioacreditacion_delete_medioacreditacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomedioacreditacion',
            options={'ordering': ['-ultima_modificacion'], 'verbose_name': 'Tipo de Medio de Acreditación', 'verbose_name_plural': 'Tipos de Medios de Acreditación'},
        ),
        migrations.RemoveField(
            model_name='tipomedioacreditacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tipomedioacreditacion',
            name='codigo',
            field=models.SlugField(default='generico', help_text='Código interno (ej: sipap, billetera, pickup)', unique=True),
        ),
        migrations.AddField(
            model_name='tipomedioacreditacion',
            name='moneda_predeterminada',
            field=models.CharField(default='PYG', help_text='Moneda principal que maneja este medio', max_length=10),
        ),
        migrations.AddField(
            model_name='tipomedioacreditacion',
            name='requiere_datos_extra',
            field=models.BooleanField(default=True, help_text='Indica si el cliente debe cargar datos adicionales (ej: número de cuenta, alias, etc.)'),
        ),
        migrations.AlterField(
            model_name='tipomedioacreditacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipomedioacreditacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
