# Generated by Django 5.2.5 on 2025-09-22 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0006_alter_tipomedioacreditacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(help_text='Identificador interno (ej: transferencia, billetera, pickup, crypto)', unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Medio',
                'verbose_name_plural': 'Categorías de Medios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='tipomedioacreditacion',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='tipomedioacreditacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='tipomedioacreditacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='medios_acreditacion.categoriamedio'),
            preserve_default=False,
        ),
    ]
