# Generated by Django 5.2.5 on 2025-09-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0007_categoriamedio_remove_tipomedioacreditacion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamedio',
            options={'ordering': ['-ultima_modificacion'], 'verbose_name': 'Medio de Acreditación', 'verbose_name_plural': 'Medios de Acreditación'},
        ),
        migrations.AddField(
            model_name='categoriamedio',
            name='moneda_predeterminada',
            field=models.CharField(default='PYG', help_text='Moneda principal que maneja este medio', max_length=10),
        ),
        migrations.AddField(
            model_name='categoriamedio',
            name='requiere_datos_extra',
            field=models.BooleanField(default=True, help_text='Si el cliente debe cargar datos adicionales (número de cuenta, alias, etc.)'),
        ),
        migrations.AlterField(
            model_name='categoriamedio',
            name='codigo',
            field=models.SlugField(help_text='Código interno (ej: transferencia, billetera, pickup)', unique=True),
        ),
        migrations.DeleteModel(
            name='TipoMedioAcreditacion',
        ),
    ]
