# Generated by Django 5.2.5 on 2025-09-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0008_alter_categoriamedio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamedio',
            name='codigo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('billetera', 'Billetera Electrónica'), ('pickup', 'Retiro en Ventanilla (Pickup)')], help_text='Seleccione el tipo de medio (ej: transferencia, billetera, pickup)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriamedio',
            name='moneda_predeterminada',
            field=models.CharField(default='PYG', editable=False, max_length=10),
        ),
    ]
