# Generated by Django 5.2.5 on 2025-09-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0009_alter_categoriamedio_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriamedio',
            name='nombre',
        ),
    ]
