# Generated by Django 5.2.5 on 2025-09-23 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_merge_20250914_2011'),
        ('medios_acreditacion', '0010_remove_categoriamedio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoMedioAcreditacion',
            fields=[
                ('id_campo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del campo')),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('telefono', 'Teléfono'), ('email', 'Email'), ('ruc', 'RUC')], default='texto', max_length=20)),
                ('obligatorio', models.BooleanField(default=True)),
                ('regex', models.CharField(blank=True, help_text='Expresión regular opcional', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedioAcreditacionCliente',
            fields=[
                ('id_medio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datos', models.JSONField(default=dict, verbose_name='Datos del medio')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedioAcreditacion',
            fields=[
                ('id_tipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriaMedio',
        ),
        migrations.AddField(
            model_name='medioacreditacioncliente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_cliente', to='medios_acreditacion.tipomedioacreditacion'),
        ),
        migrations.AddField(
            model_name='campomedioacreditacion',
            name='tipo_medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='medios_acreditacion.tipomedioacreditacion'),
        ),
    ]
