# Generated by Django 5.2.5 on 2025-09-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0011_campomedioacreditacion_medioacreditacioncliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomedioacreditacion',
            name='regex',
            field=models.CharField(blank=True, choices=[('', 'Sin validación extra'), ('^[0-9]+$', 'Solo números'), ('^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$', 'Solo letras'), ('^[^@]+@[^@]+\\.[^@]+$', 'Correo electrónico válido'), ('^\\d{9,15}$', 'Teléfono (9 a 15 dígitos)'), ('^\\d{6,8}-\\d{1}$', 'RUC (########-#)')], help_text='Regla de validación que se aplicará automáticamente', max_length=200, null=True, verbose_name='Validación extra'),
        ),
    ]
