# Generated by Django 5.2.5 on 2025-09-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0012_alter_campomedioacreditacion_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='campomedioacreditacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
