# Generated by Django 5.2.5 on 2025-09-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0013_campomedioacreditacion_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomedioacreditacion',
            options={'permissions': [('access_medios_acreditacion', 'Puede gestionar métodos de pago (Tipos de Medio y Campos)')]},
        ),
    ]
