# Generated by Django 5.2.5 on 2025-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0014_alter_tipomedioacreditacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medioacreditacioncliente',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
