# Generated by Django 5.2.5 on 2025-09-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_medioacreditacion'),
        ('medios_acreditacion', '0015_medioacreditacioncliente_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='medioacreditacioncliente',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='medioacreditacioncliente',
            constraint=models.UniqueConstraint(condition=models.Q(('predeterminado', True)), fields=('cliente',), name='uniq_default_medio_por_cliente'),
        ),
    ]
