# Generated by Django 5.2.5 on 2025-10-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalistaPanelPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_analista_dashboard', 'Puede acceder al dashboard del Analista'), ('access_exchange_rates', 'Puede acceder a Gestión de Tasas (ajuste manual + auditoría)'), ('view_profits_module', 'Puede ver el módulo de Ganancias (cuando esté disponible)')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
